### ISSUE TITLE
Develop the Share feature in the app

### ISSUE THREAD

**Issue by jddeep** [fossasia/neurolab-android#450] opened 2019-08-31 13:39 UTC
**Actual Behaviour.**  
Missing Share feature in the app.

**Expected Behaviour**  
Develop the Share feature in the app.

**Steps to reproduce it**  
Check the bottom option in the navigation drawer of the app.

**Additional context**  
By share, we mean sharing a logged/recorded/test dataset to another user's device.

**Would you like to work on the issue?**
Issue for Codeheat.

**Comment by adityastic** [comment] 2019-09-07 10:44
I'd like to work on it

**Comment by rob729** [comment] 2019-09-08 10:25
@adityastic Can I work on this issue as you are already working on other issues?

**Comment by adityastic** [comment] 2019-09-08 14:20
@rob729 sure, go ahead

**Comment by rob729** [comment] 2019-09-08 15:56
@jddeep @adityastic Do you have any plan/idea on how to implement this feature?

**Comment by jddeep** [comment] 2019-09-08 16:12
@rob729 Please read the whole issue description and additional context. Thanks.

**Comment by adityastic** [comment] 2019-09-08 16:31
> @jddeep @adityastic Do you have any plan/idea on how to implement this feature?

The issue is straightforward, nothing tough. As said by @jddeep issue description should be enough

**Comment by Bhavnaharitsa** [comment] 2019-09-16 15:21
@jddeep Can I work on this?

**Comment by jddeep** [comment] 2019-09-16 15:26
> @jddeep Can I work on this?

@rob729 Any updates on this?

**Comment by jddeep** [comment] 2019-09-16 15:34
@Bhavnaharitsa please wait till @rob729 gives me any updates. Otherwise I will assign this to you.

**Comment by rob729** [comment] 2019-09-16 16:10
@Bhavnaharitsa  you can work on this issue.

**Comment by nikhil097** [comment] 2019-09-19 16:58
@Bhavnaharitsa Are you working on this issue?

**Comment by Bhavnaharitsa** [comment] 2019-09-19 23:55
@nikhil097 Yes, I am. Please find new issues :)

**Comment by AshutoshDas07** [comment] 2019-09-28 16:26
can i take up this issue?

**Comment by dipu989** [comment] 2019-09-30 18:53
@Bhavnaharitsa If you are no working on this issue, @jddeep can you assign this to me after confirmation?
Thanks!

**Comment by jddeep** [comment] 2019-10-01 08:11
@dipu989 Go ahead :+1:

**Closed as completed** 2019-10-17 06:57 UTC
Labels: feature, Codeheat
