### ISSUE TITLE
Meditate player restarts on orientation change.

### ISSUE THREAD

**Issue by AkshobhyaP** [fossasia/neurolab-android#587] opened 2020-01-19 17:43 UTC
**Describe the bug**
Meditate player restarts from it's current time in seek-bar if the orientation is changed.

**Expected Behavior**
The sound should play from the same instance where it was paused before orientation change.

**Steps to reproduce it**
Play any sound in Meditate activity till a certain time and pause it. -> Change screen orientation -> Play the sound again.

**Screenshots of the issue**
![20200119_225933](https://user-images.githubusercontent.com/18425237/72685488-a6ab9680-3b10-11ea-8a7b-ee039a968ca8.gif)

**System Information**
<table>
<tr>
  <td>Device</td><td>Oneplus 3</td>
</tr>
<tr>
  <td>Android version/OS</td><td>Pie 9.0</td>
</tr>
</table>

**Would you like to work on the issue?**
YES

**Comment by AkshobhyaP** [comment] 2020-01-19 17:44
@adityastic @jddeep

**Comment by ho-dor** [comment] 2020-01-20 01:47
@AkshobhyaP duplicate of #585

**Closed as completed by ho-dor** 2020-01-20 01:47 UTC
